### ISSUE TITLE
WPAdverts Snippets - Ads By Author

### ISSUE THREAD

**Issue by Garigolo** [simpliko/wpadverts-snippets#4]
When activating WPAdverts Snippet - Ads By Author I'm getting this warning: Illegal string offset 'search_bar' in /home4/wack6s0abnmm/public_html/wp-content/plugins/code-snippets/php/snippet-ops.php(352) : eval()'d code on line 45

**Comment by gwin** [comment]
Thanks for feedback, i updated Ads By Author snippet, specifically line 49, it should not trigger this warning.
